//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(EmployeeMetaData))]
    public partial class Employee
    {
        public int employeeId { get; set; }
        public string name { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string city { get; set; }
        public int departmentID { get; set; }
    
        public virtual Department Department { get; set; }
    }

    public class EmployeeMetaData
    {
        [Required]
        [Display(Name="Employee Name")]
        public string name { get; set; }
        [Required]
        [Display(Name = "Date of Birth")]
        public System.DateTime dateOfBirth { get; set; }
        [Required]
        [Display(Name = "City")]
        public string city { get; set; }
        [Required]
        [Display(Name = "Department")]
        public int departmentID { get; set; }
    }
}
